config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :comments
  resources :users, only: [:index, :show, :destroy, :update, :create] do
    resources :contacts, only: :index
    resources :comments, only: :index
  end
  resources :contacts, only: [:show, :destroy, :update, :create] do
    resources :comments, only: :index
  end
  resources :contact_shares, only: [:index, :create, :destroy]

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id          :integer          not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  target_id   :integer
#  target_type :string
#  user_id     :integer          not null
#  text        :text             not null
#

class Comment < ActiveRecord::Base
  validates :target_id, :target_type, :user_id, :text, presence: true

  belongs_to :target, polymorphic: true
  belongs_to :author,
    foreign_key: :user_id,
    class_name: :User
end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name       :string           not null
#  email      :string           not null
#  user_id    :integer          not null
#

class Contact < ActiveRecord::Base
  validates :user_id, uniqueness: { scope: :email }
  validates :name, :email, :user_id, presence: true

  belongs_to :owner,
    foreign_key: :user_id,
    class_name: :User,
    dependent: :destroy

  has_many :contact_shares
  has_many :shared_users, through: :contact_shares
  has_many :comments, as: :target
end

app/models/contact_share.rb
# == Schema Information
#
# Table name: contact_shares
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  contact_id :integer          not null
#  user_id    :integer          not null
#

class ContactShare < ActiveRecord::Base
  validates :contact_id, :user_id, presence: true
  validates :user_id, uniqueness: { scope: :contact_id }

  belongs_to :contact
  belongs_to :user, dependent: :destroy
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  username   :string           not null
#

class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true

  has_many :contacts
  has_many :contact_shares
  has_many :shared_contacts,
    through: :contact_shares,
    source: :contact
  has_many :comments, as: :target
  has_many :authored_comments,
    foreign_key: :user_id,
    class_name: :Comment

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/contact_shares_controller.rb
class ContactSharesController < ApplicationController
  def index
    @contact_shares = ContactShare.all

    render json: @contact_shares
  end


  def create
    @contact_share = ContactShare.new(contact_share_params)

    if @contact_share.save
      render json: @contact_share
    else
      render(
        json: @contact_share.errors.full_messages,
        status: :unprocessable_entity
      )
    end
  end

  def destroy
    @contact_share = ContactShare.find(params[:id])
    @contact_share.destroy

    render json: @contact_share
  end

  private

  def contact_share_params
    params.require(:contact_share).permit(:user_id, :contact_id)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @contacts = @user.contacts + @user.shared_contacts
    
    render json: @contacts
  end

  def show
    @contact = Contact.find(params[:id])

    render json: @contact
  end

  def update
    @contact = Contact.find(params[:id])

    if @contact.update(user_params)
      render json: @contact
    else
      render(
        json: @contact.errors.full_messages,
        status: :unprocessable_entity
      )
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    render json: @contact
  end

  def create
    @contact = contacts.new(contact_params)
    if @contact.save
      render json: @contact
    else
      render(
        json: @contact.errors.full_messages,
        status: :unprocessable_entity
      )
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:user_id, :contact_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all

    # render json: @users
  end

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render json: @user
    else
      render(
        json: @user.errors.full_messages, status: :unprocessable_entity
      )
    end
  end

  def show
    @user = User.find(params[:id])

    render 'profile'
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      render json: @user
    else
      render(
        json: @user.errors.full_messages, status: :unprocessable_entity
      )
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    render json: @user
  end

  def delete_contact_share_for(contact)
    
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contact_shares_helper.rb
module ContactSharesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstRoutes</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Users</title>
  </head>
  <body>
    <section>
      <h1>All Users</h1>
      <ul>
        <% @users.each do |user| %>
          <li><%= link_to user.username, user %></li>
        <% end %>
      </ul>
    </section>
  </body>
</html>

app/views/users/profile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User Profile</title>
  </head>
  <body>
    <h1>User Profile: <%= @user.username %></h1>
    <table>
      <tname><h3>Owned Contacts:</h3></tname>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Owner</th>
      <% @user.contacts.each do |contact| %>
        <tr>
          <td><%= contact.name %></td>
          <td><%= contact.email %></td>
          <td><%= link_to contact.owner.username, contact.owner %></td>
          <td><%= link_to 'Show', contact %></td>
        </tr>
      <% end %>
    </table>

    <table>
      <tname><h3>Shared Contacts:</h3></tname>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Owner</th>
      <% @user.shared_contacts.each do |contact| %>
        <tr>
          <td><%= contact.name %></td>
          <td><%= contact.email %></td>
          <td><%= link_to contact.owner.username, contact.owner %></td>
          <td><%= link_to 'Show', contact %></td>
          <td><%= button_to('Delete', contact,
              method: "delete", remote: true,
              data: { confirm: 'Are you sure?' }) %></td>
        </tr>
      <% end %>
    </table>

    <table>
      <tname><h3>Comments:</h3></tname>
      <tr>
        <th>Text</th>
        <th>Owner</th>
      <% @user.comments.each do |comment| %>
        <tr>
          <td><%= comment.text %></td>
          <td><%= link_to comment.author.username, comment.author %></td>
          <td><%= link_to 'Show', comment %></td>
        </tr>
      <% end %>
    </table>

    <table>
      <tname><h3>Authored comments:</h3></tname>
      <tr>
        <th>Text</th>
        <th>Target</th>
      <% @user.authored_comments.each do |comment| %>
        <tr>
          <td><%= comment.text %></td>
          <td><%= link_to "#{comment.target_type} #{comment.target_id}", comment.target %></td>
          <td><%= link_to 'Show', comment %></td>
        </tr>
      <% end %>
    </table>

    <footer style="margin-top:50px">
      <%= link_to 'All users', users_path %>
    </footer>
  </body>
</html>